// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RcppMySMC_RcppExports_h
#define RcppMySMC_RcppExports_h

#include <Rcpp.h>

namespace RcppMySMC {

    using namespace Rcpp;

    namespace {
        void validateExported(const std::string& sig) {
            static bool(*p_validateExported)(const std::string&) = Rcpp::GetCppCallable("RcppMySMC", "RcppMySMC_RcppExports", "RcppExports_validateExported");
            if (!p_validateExported(sig))
                throw Rcpp::function_not_exported("Function '" + sig + "' not found in RcppMySMC");
        }
    }

    inline SEXP pfPoissonEdge1DSelfOrg(NumericVector observations, int numOfParticles, double sigma_alpha, double alpha0, double beta0, double lambda0, double lambdaMax) {
        static SEXP(*p_pfPoissonEdge1DSelfOrg)(NumericVector,int,double,double,double,double,double) = NULL;
        if (p_pfPoissonEdge1DSelfOrg == NULL) {
            validateExported("SEXP(*pfPoissonEdge1DSelfOrg)(NumericVector,int,double,double,double,double,double)");
            p_pfPoissonEdge1DSelfOrg = Rcpp::GetCppCallable("RcppMySMC", "RcppMySMC_RcppExports", "pfPoissonEdge1DSelfOrg");
        }
        return p_pfPoissonEdge1DSelfOrg(observations,numOfParticles,sigma_alpha,alpha0,beta0,lambda0,lambdaMax);
    }

    inline SEXP pfPoissonEdge1DSelfOrgUsingOneStep(NumericVector observations, int numOfParticles, double sigma_alpha, double alpha0, double beta0, double lambda0, double lambdaMax) {
        static SEXP(*p_pfPoissonEdge1DSelfOrgUsingOneStep)(NumericVector,int,double,double,double,double,double) = NULL;
        if (p_pfPoissonEdge1DSelfOrgUsingOneStep == NULL) {
            validateExported("SEXP(*pfPoissonEdge1DSelfOrgUsingOneStep)(NumericVector,int,double,double,double,double,double)");
            p_pfPoissonEdge1DSelfOrgUsingOneStep = Rcpp::GetCppCallable("RcppMySMC", "RcppMySMC_RcppExports", "pfPoissonEdge1DSelfOrgUsingOneStep");
        }
        return p_pfPoissonEdge1DSelfOrgUsingOneStep(observations,numOfParticles,sigma_alpha,alpha0,beta0,lambda0,lambdaMax);
    }

}

#endif // RcppMySMC_RcppExports_h
