// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

SEXP myfilter1(unsigned long particleNum, NumericVector observation, bool useF, Function f);

static bool validateExported(const std::string& sig) {
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("SEXP(*myfilter1)(unsigned long,NumericVector,bool,Function)");
    }
    return signatures.find(sig) != signatures.end();
}

RCPP_MODULE(RcppMySMC_RcppExports) {
    Rcpp::function("myfilter1", &myfilter1, Rcpp::List::create(Rcpp::Named("particleNum"), Rcpp::Named("observation"), Rcpp::Named("useF"), Rcpp::Named("f")));
    Rcpp::function("RcppExports_validateExported", &validateExported);
}
