# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp::loadModule("RcppMySMC_RcppExports", 
    what = c("myfilter1",
             "pfEdge1D",
             "pfEdge1DSelfOrg",
             "pfPoissonEdge1DSelfOrg",
             "pfSimple1D"))
